name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Smoke UCI
        shell: pwsh
        run: ./Scripts/smoke-uci.ps1

  package:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build MSIX
        run: pwsh ./Scripts/build-msix.ps1 -Configuration Release

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chessapp-MSIX
          path: packaging/Artifacts/*.msix
