name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore --configuration Release

      # Run tests only if test projects exist to avoid failing the job on empty test sets
      - name: Run unit tests (if present)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $projs = Get-ChildItem -Recurse -Filter *.csproj | Where-Object {
            Select-String -Path $_.FullName -SimpleMatch '<IsTestProject>true</IsTestProject>' -Quiet
          } | ForEach-Object { $_.FullName }
          if (-not $projs -or $projs.Count -eq 0) {
            Write-Host 'No test projects found. Skipping dotnet test.'
            exit 0
          }
          foreach ($p in $projs) {
            Write-Host "Testing $p"
            dotnet test $p --no-build --configuration Release --nologo
          }

      - name: Smoke UCI
        shell: pwsh
        run: ./Scripts/smoke-uci.ps1
